ci-cd-pipeline.yaml file is updated

diff --git a/.github/workflows/ci-cd-pipeline.yaml b/.github/workflows/ci-cd-pipeline.yaml
--- a/.github/workflows/ci-cd-pipeline.yaml
+++ b/.github/workflows/ci-cd-pipeline.yaml
@@ -44,28 +44,28 @@ jobs:
       run: |
         echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
         docker push ogulcanakca/stock-prediction-app-for-server
-
     - name: Deploy to AWS EC2
       run: |
         echo "${{ secrets.SSH_KEY }}" > /tmp/id_rsa
         chmod 600 /tmp/id_rsa
         ssh -o StrictHostKeyChecking=no -i /tmp/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
         if [ ! -d "/home/ubuntu/TimeSeriesForecastAPI-withServer" ]; then
-          mkdir -p /home/ubuntu/TimeSeriesForecastAPI-withServer
-          git clone https://github.com/ogulcanakca/TimeSeriesForecastAPI-withServer.git /home/ubuntu/TimeSeriesForecastAPI-withServer
+          git clone git@github.com:ogulcanakca/TimeSeriesForecastAPI-withServer.git /home/ubuntu/TimeSeriesForecastAPI-withServer
         else
           cd /home/ubuntu/TimeSeriesForecastAPI-withServer
           git pull origin main
         fi
         cd /home/ubuntu/TimeSeriesForecastAPI-withServer
-        docker-compose pull
-        docker-compose up -d
+        if [ -f "docker-compose.yml" ]; then
+          docker-compose pull
+          docker-compose up -d
+        else
+          echo "docker-compose.yml file not found!"
+          exit 1
+        fi
         EOF
       env:
         SSH_KEY: ${{ secrets.SSH_KEY }}
         SSH_USER: ${{ secrets.SSH_USER }}
         SSH_HOST: ${{ secrets.SSH_HOST }}
-        
-
-
-        
+      
